# Generated by Django 5.2.1 on 2025-06-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerinventoryitem',
            name='division_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
