# Generated by Django 5.2.1 on 2025-06-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_managerinventoryitem_division_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_division_id', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='managerinventoryitem',
            name='division_name',
            field=models.CharField(blank=True, help_text='Division name from Manager.io', max_length=255, null=True),
        ),
    ]
