# Generated by Django 5.2.1 on 2025-06-22 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_managerdivision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorder',
            options={'ordering': ['-scheduled_date', 'production_category_code', 'item_name']},
        ),
        migrations.RenameField(
            model_name='productionorder',
            old_name='actual_yield',
            new_name='actual_quantity',
        ),
        migrations.RenameField(
            model_name='productionorder',
            old_name='production_quantity',
            new_name='planned_quantity',
        ),
        migrations.RemoveField(
            model_name='productioncategory',
            name='assigned_person',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='batch_quantity',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='production_category',
        ),
        migrations.RemoveField(
            model_name='productionshift',
            name='categories',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='is_split_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.productionorder'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='production_category_code',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='split_assignments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='variance_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('partial', 'Partially Completed')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, help_text='Division from Manager.io', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProductionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_ordered', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_required', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recommended_production', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('manual_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.managerinventoryitem')),
                ('orders', models.ManyToManyField(blank=True, to='recipes.order')),
                ('production_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.productioncategory')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.productionshift')),
            ],
            options={
                'ordering': ['-date', 'production_category__code'],
                'unique_together': {('date', 'shift', 'finished_good')},
            },
        ),
    ]
