# Generated by Django 5.2.1 on 2025-06-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_productionorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncategory',
            name='code',
            field=models.CharField(choices=[('Production-001', 'Bakery, Frozen & Savory - Mr. Sabuz'), ('Production-002', 'Cake & Pastry - Mr. Rakib'), ('Production-003', 'Resultant Items - Mr. Justin')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='production_category_code',
            field=models.CharField(default='Production-001', max_length=20),
        ),
    ]
