# Generated by Django 5.2.1 on 2025-06-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
