# Generated by Django 5.2.1 on 2025-06-23 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('customer', 'Customer'), ('manager', 'Manager')], max_length=20)),
                ('page', models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Inventory'), ('recipes', 'Recipes'), ('production', 'Production'), ('orders', 'Orders'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=20)),
                ('can_access', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Page Permission',
                'verbose_name_plural': 'Page Permissions',
                'unique_together': {('role', 'page')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('customer', 'Customer'), ('manager', 'Manager')], default='customer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
